version: '3.8'
services:
  api-crypto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-crypto
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:dev'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis-crypto
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - crypto-net

  redis-crypto:
    container_name: redis-crypto
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    volumes:
      - redis-data:/data
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge

volumes:
  redis-data:
    driver: local
